## ===========================
## modules/build.yml
## ===========================
steps:

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: build
      projects:  $(packageName)/$(packageName)/$(packageName).csproj
      # arguments: --configuration $(buildConfiguration) 
      arguments: >
          --configuration $(buildConfiguration)
          /p:PublishReadyToRun=false
      # arguments: --configuration $(buildConfiguration) --verbosity detailed
  
 